### ISSUE TITLE
Login failed : error 500 ?

### ISSUE THREAD

**Issue by DiesIrae** [steffow/meteor-accounts-saml#11]
Hi,

Thanks for this awesome lib! :-)

When there is no user email corresponding to the SAML connexion, an error shows in the server console : `Exception while invoking method 'login' { stack: 'Error: Could not find an existing user with supplied email`.

The error is pretty explicit, but how can I send it back to the client ? On the client side, I have a general 500 error. Is it normal? It seems to me a 403 would have been more logical.

I tried to fidget with `Accounts.onLoginFailure(callback)`. The callback is triggered, but I couldn't figure out how to send an explicit error to the client.

Thanks!

**Comment by steffow** [comment]
Let me dig in to this. Currently not sure if it violates spec (probably not).
Meanwhile: there is new option to dynamically create user, if no matching Meteor user could be found.
Simply set "dynamicProfile": true in settings.js

**Comment by DiesIrae** [comment]
Hi @steffow,

Thanks for the answer and the "dynamicProfile" info, it could be useful for me in the future.

For now I need to throw an error, but it needs to be a meaningful error. Do you know where I can do this on the server ?

**Comment by steffow** [comment]
Would it help if we could make the attribute to look for configurable? So you could eg change that from email to phoneNumber or do you generally want to getter better error code if user cannot be found?
I’ll look into the 403 thing but requires some spec reading....

**Comment by DiesIrae** [comment]
Nope email is perfectly fine. I only need to inform the user that he is well connected, but he does not exists in my environment.

Actually the http code is a thing, but I only need to recognize the error. I took a look at the code: instead of throwing a js standard error on line 123, maybe it could throw a `Meteor.Error`, with meaningful error code & reason?

**Comment by steffow** [comment]
This is reported in console log. "User not found. Will dynamically create one" - this basically corresponds to Auto Federation and is configurable.
