### ISSUE TITLE
Shibboleth Support

### ISSUE THREAD

**Issue by DerekTBrown** [steffow/meteor-accounts-saml#13]
I am looking to add Shibboleth authentication to my package (which I guess would be classified as a provider for SAML).  Could I submit a PR to add Shibboleth Auth to your package? Any advice for formatting the PR?

**Comment by steffow** [comment]
Best way for me would be to provide a PR against the dev (!!) branch. Do you have a Shib IdP setup for quick testing?

**Comment by DerekTBrown** [comment]
@steffow I think this should work https://www.testshib.org/
