### ISSUE TITLE
Question: Working with Shibboleth IdP

### ISSUE THREAD

**Issue by jykae** [steffow/meteor-accounts-saml#2]
Just a question, would this work with Shibboleth-based IdP ?

**Comment by steffow** [comment]
I have no idea; didn’t try it - you have to check.

**Comment by jykae** [comment]
@steffow Can you tell how we can define additional attribute mappings?

**Comment by jykae** [comment]
I am interested to contribute for this thing on roadmap, "Support for different SAML Bindings". 
Working on this under our organization https://github.com/apinf/meteor-accounts-saml

We have couple of SSO implementations that we are testing this package. Other one is open source and based on Shibboleth2.
