### ISSUE TITLE
Add support for encrypted assertions (by PR)

### ISSUE THREAD

**Issue by gerbsen** [steffow/meteor-accounts-saml#29]
hey @steffow, we have installed rocket.chat in a pretty large environment with possibly 60k+ users. since our IT department forces us to use encrypted assertions (please forgive me if the wording doesn't make 100% sense, I currently feel responsible but did not code so far on this project) and your plugin does not support it (I've been told), we hacked it into the the `meteor-accounts-saml` lib/file that is delivered with Rocket.Chat. Since things have settled down a little and we also experienced some bugs with our installation, we thought it's time to give back. We are in the process of preparing a pull request and I wanted to ask you if you would willing to accept it, if of course it meets your quality criteria. Cheers and thanks for your work, daniel

**Comment by steffow** [comment]
Hey Daniel.

Sure - happy to receive PR. Couple of things which saves my time:

a. Could y do a rebase and then run yr tests? 
b. By encry assertion you mean an assertion that uses XMLenc to encrypt data, right? Can this be done using the metadata we currently use?
c. Make sure you send PR against dev branch or fork off dev branch (eg using git-flow)
d. Are you aware of things that might backward compat?

Do let me know, if you have questions

Best

Steffo

**Comment by anicoa** [comment]
Hey Steffo,

b. it's XMLenc encrypted data and we are using xml-encryption to decrypt. It can be done with current metadata. In our case encryption is forced on IDP side and settings in 'our' metadata regarding encrypted assertion/nameid are ignored. A next step could be to provide encryption in the local metadata but thats no necessary.

regards
nico

**Comment by gerbsen** [comment]
hey @steffow I wanted to check up on the current status. Cheers, Daniel

**Comment by steffow** [comment]
Yep. Just tested - looks good. One minor comment. Could y also pls add sth to the README on how to use this?

**Comment by steffow** [comment]
Tagged 0.0.16
