### ISSUE TITLE
Not able to login with WSO2 provider

### ISSUE THREAD

**Issue by deevant07** [steffow/meteor-accounts-saml#3]
I have tried setting up WSO2 provider for SAML authentication but facing issue when user is being logged in meteor. Ideally it has to create the user in Users collection for the first time but it shows "Could not find an existing user" 

Validated using the url:
http://localhost:3000/_saml/metadata/<appname>

This has responded proper SAML xml response.

I aslo tried http://localhost:3000/_saml/authorize/<appname>

which is showing me the result as 
Verified

Now i am getting an error:
I20160608-16:45:21.090(5.5)? Exception while invoking method 'login' Error: Could not find an existing user with supplied email test1@carbon.super
I20160608-16:45:21.090(5.5)?     at [object Object].Accounts.saml._loginResultForCredentialToken (packages/steffo_meteor-accounts-saml.js:114:19)
I20160608-16:45:21.091(5.5)?     at packages/accounts-base/accounts_server.js:464:32
I20160608-16:45:21.091(5.5)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:241:14)
I20160608-16:45:21.091(5.5)?     at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:461:18)
I20160608-16:45:21.092(5.5)?     at [object Object].methods.login (packages/accounts-base/accounts_server.js:524:27)
I20160608-16:45:21.092(5.5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160608-16:45:21.092(5.5)?     at packages/ddp-server/livedata_server.js:711:19
I20160608-16:45:21.092(5.5)?     at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
I20160608-16:45:21.093(5.5)?     at packages/ddp-server/livedata_server.js:709:40
I20160608-16:45:21.093(5.5)?     at [object Object]._.extend.withValue (packages/meteor.js:1100:17)

**Comment by steffow** [comment]
> On 08 Jun 2016, at 13:52, Deevab notifications@github.com wrote:
> 
> I20160608-16:45:21.090(5.5)? Exception while invoking method 'login' Error: Could not find an existing user with supplied email test1@carbon.super

Deevab, hat happens if you create a local user with that mail addr?

Note that currently we need a local user to federate and dynamic profile creation is not supported (unless someone writes it).

Best

Steffo
