### ISSUE TITLE
question: about settings parameters

### ISSUE THREAD

**Issue by Gobliins** [steffow/meteor-accounts-saml#4]
Does this lib also work without the last three parameters in the settings

 "idpSLORedirectURL": "http://openam.idp.io/openam/IDPSloRedirect/metaAlias/zimt/idp",
 "privateKeyFile": "certs/mykey.pem",  // path is relative to $METEOR-PROJECT/private
 "publicCertFile": "certs/mycert.pem"  // eg $METEOR-PROJECT/private/certs/mycert.pem

?

I've used the [https://atmospherejs.com/natestrauser/accounts-saml](https://atmospherejs.com/natestrauser/accounts-saml) and here the other 4 parameters (issuer, entrypoint, provider, cert) were enough.

**Comment by steffow** [comment]
Well you need at least the privKey/pubCert combo as trust in SAML is established via PKC.

Makes sense?

**Comment by Gobliins** [comment]
Coming from OAuth2 i am not so familiar with SAML and dig. signatures.
So the "Cert" parameter takes the Certficate from the IDP?
And the privateKey/publicCert i generate myself?

**Comment by steffow** [comment]
Think of it a mutual SSL authN. You can generate yourself but trust chain must be valid.

**Comment by Gobliins** [comment]
Ok seems like i made it working, we can close this issue then, thx.

**Comment by Gobliins** [comment]
One more thing, when i enter the issuer:
` "issuer" : "https://myserverurl.de" `
is it sent in the saml request as:
` "https://myserverurl.de" `or `"myserverurl.de"` ?
