### ISSUE TITLE
Error: Unexpected SAML service AZURE

### ISSUE THREAD

**Issue by Gobliins** [steffow/meteor-accounts-saml#5]
Hello,
i try to make a SAML login on Azure but i am getting this error:

```
`Error: Unexpected SAML service AZURE`
```

It seems like the provider is taken from:

`<template name="samlLogin">`
`<a href="#" class="saml-login" data-provider="AZURE">AZURE</a>`
`</template>`

I have edited my meteor.settings as described on main page with Azure configuration.

**Comment by steffow** [comment]
I have to tested Azure. What should work is if you deploy OpenAM on Azure.

**Comment by steffow** [comment]
I have NOT tested Azure ;-)

Sorry for the typo.

> On 27 Sep 2016, at 10:34, Steffo Weber steffo.weber@gmail.com wrote:
> 
> I have to tested Azure. What should work is if you deploy OpenAM on Azure.
> 
> > On 27 Sep 2016, at 10:18, Gobliins notifications@github.com wrote:
> > 
> > Hello,
> > i try to make a SAML login on Azure but i am getting this error:
> > 
> > `Error: Unexpected SAML service AZURE`
> > 
> > It seems like the provider is taken from:
> > 
> > <template name="samlLogin">
> > <a href="#" class="saml-login" data-provider="AZURE">AZURE</a>
> > </template>
> > 
> > I have edited my meteor.settings as described on main page with Azure configuration.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.

—

Dr Steffo Weber | Architect

http://flip.it/caxRa
Skype: steffo.weber

**Comment by Gobliins** [comment]
I have thought so, still i wonder how i could manage to get it work on ADFS 3.0, which should be similar to Azure AD.

**Comment by Gobliins** [comment]
NVM it was a typo _shame on me_ issue can be closed :)
