### ISSUE TITLE
doesn't work with multiple process.

### ISSUE THREAD

**Issue by shrynx** [steffow/meteor-accounts-saml#7]
I am using pm2 for the meteor app. Sometimes process 1 generates the request but response comes in process 2 and it doesn't have the credential token to match and hence fails. One way would be to save the tokens temporarily in a database and read from it. Any suggestions ?

**Comment by steffow** [comment]
Sounds like like LB issue. Can you share more details on yr setup (LB, Ports etc)?

**Comment by shrynx** [comment]
@steffow yes, we are using pm2 for load balancing, spinning up 3 processes. Do you suggest another approach ?
The application is running on 3000, 3001 and 3002 and then load balanced using pm2 further https via nginx.

**Comment by steffow** [comment]
You'd need to insert a cookie or sth to provide session persistence. LBs can do this.
