### ISSUE TITLE
SAML Integration missing hash algorithm

### ISSUE THREAD

**Issue by gerbsen** [steffow/meteor-accounts-saml#8]
hey there,
I've this problem which I described [here](https://github.com/RocketChat/Rocket.Chat/issues/6441): 

    Sorry, an annoying error occured
    Error: hash algorithm 'http://www.w3.org/2001/04/xmlenc#sha512' is not supported
    Close Window

but no one is answering, I thought maybe let's try it here. 

any help is very much appreciated!
thanks, daniel

**Comment by gerbsen** [comment]
@steffow hey sorry for being annoying

**Comment by steffow** [comment]
Think this is an issue w the xml-crypto NPM which doesnt support SHA512 https://github.com/ZheFeng/xml-crypto <https://github.com/ZheFeng/xml-crypto>

**Comment by gerbsen** [comment]
hey @steffow, thank you very much for this information! If I go to the original repo (https://github.com/yaronn/xml-crypto) SHA 512 is listed as supported. Do you have any idea where I should turn to?

**Comment by steffow** [comment]
Indeed. Would need to check which source npm module is build from. Anyway, you have the source....

Steffo

**Comment by steffow** [comment]
I’ve just updated the package. If that doesn’t resolve yr issue, can you send me sth to reproduce?

**Comment by gerbsen** [comment]
Hey @steffow, thank you! So far I've installed Rocket.Chat with this [Dockerfile](https://github.com/RocketChat/Docker.Official.Image/blob/a721d599218803d2acb27f92b11d2cdcf0a226d5/Dockerfile). Will have to see how I can integrate this... Are you associated with Rocket.Chat, e.g. do you see any chance they will integrate your version bump into there release?

**Comment by steffow** [comment]
No. I have no relation w them. Seems as if if they forked the package. Main changes are in https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/meteor-accounts-saml/package.js <https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/meteor-accounts-saml/package.js>.

**Comment by gerbsen** [comment]
So if I understand this correctly, I would need them to change to xml-crpyto to 0.9.0 pray that it does break anything else? (Sorry, but I'm not really a JS developer) But your help is very much appreciated!

**Comment by steffow** [comment]
Prob a good idea to grab all the new npm’s.
But yes, that’s all I did. I couldnt test if it resolves yr missing hash issue though.

So use:

Npm.depends({
    "xml2js": "0.4.17",
    "body-parser": "1.17.1",
    "sax": "1.2.2",
    "xmlbuilder": "8.2.2",
    "ejs": "2.5.6",
    "async": "2.3.0",
    "lodash":"4.17.4",
    "xpath": "0.0.24",
    "node-forge": "0.7.1",
    "xpath.js": "1.0.7",
    "xmldom": "0.1.27",
    "connect": "3.6.0",
    "querystring": "0.2.0",
    "xml-encryption": "0.10.0",
    "xml-crypto": "0.9.0"
});

Also, “random” must be included in server packages.

**Comment by steffow** [comment]
I'm closing this issue as no test case is available; Rocket apparantly modified the code: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/meteor-accounts-saml/CHANGELOG.md
